### PR TITLE
minor typos, PrePubMed, ScienceOpen

### PR DESCRIPTION
**Pull request by aleimba**
Hi @pschloss,

great article, I'm positive you covered all important issues nicely. While reading I discovered some minor typos. Also added a sentence on PrePubMed (http://www.prepubmed.org/), which indexes all preprint servers, and ScienceOpen (https://www.scienceopen.com/), which indexes arXiv.

I didn't quite get your writing process so edited file *./submission/Schloss_PrePrints_mBio_2017.Rmd*, but did not add references to your *reference.bib* bibTeX file (just added hyperlinks in the text). I hope that's alright. Unfortunately the git diff is not really clear with long sentences.

Best,
Andreas

P.S.: I'm running an Open Science Session with @konrad at the German Microbiology Society conference in the begin of March (DGHM and VAAM, http://www.microbiology-infection.de/), thus might use your figure ;-). No idea how the crowd will react to Open Science, let's see.

### CODE REVIEW

**Comment by pschloss** [comment]
Thanks a lot, Andreas! I really appreciate the contribution and will work on bringing your text in as I go through the comments I get back.

I am familiar with PrePubMed, but didn't know about ScienceOpen. To my eye I wasn't sure if PrePubMed was stable and something that would be supported long term of if it was someone's side project. The limited search (lack of AND/OR), lack of an About tab, and possible copyright infringement from PubMed with the name and styling gave me pause when I was drafting the manuscript. I know that everything preprint is in a state of flux, but would rather not have something go "poof" before the paper is published. Any thoughts?

**Comment by aleimba** [comment]
Sure, my pleasure. Since I saw your tweet about the repo, I thought I might as well put the few minor corrections in while flying over the manuscript.

You pretty much voice my concerns about PrePubMed. The branding is not ideal etc.. Nevertheless, I've been getting a stable RSS feed for quite a while now (with my usual bioRxiv batch). I guess you can talk to @OmnesResNetwork on Twitter directly (and see ['Help'](http://www.prepubmed.org/help/) instead of 'About'). But, I agree PrePubMed is a tough call (initiative/change vs. tradition/stability). Would be nice if ScienceOpen could integrate bioRxiv and PeerJPreprints. Or while I'm wishing, directly in PubMed. Let's hope that we don't get an even more fragmented preprint landscape.

That reminds me, you might also want to include a paragraph on the [ASAPbio](http://asapbio.org/) preprint initiative. Both top-down policy as well as bottom-up/grassroot initiatives have to work together.

Respective your search terms, ~~a shame you missed my first (and only) [preprint](http://biorxiv.org/content/early/2016/12/23/096479) ;-).~~ Would be great if you could choose more than one category in bioRxiv. No matter what, you will always miss some publications. But since you describe your method clearly I see no difficulties. One more advantage for PP is for PhD students/postdocs that are finishing up and leaving the lab, it's a great way to get something countable instead of a manuscript in a desk drawer.

Overall, I think the manuscript is well balanced. But, I'm a fanboy too so don't know how much that counts.

**Comment by OmnesRes** [comment]
Re PrePubMed:
Yes, I've been hearing concerns about copying the PubMed layout so I recently changed the colors. I also added a policies page: http://www.prepubmed.org/terms/

I also know there is concern about the name branding.  I guess I wasn't worried about it because bioRxiv stepped on the arXiv name brand along with their site layout.  Other sites have also followed suit with the name branding such as PsyArXiv.  Maybe I should have named the site PrePubBio or something since I focus on biology preprints, and then others could have made PrePubMath, etc. if they wanted.

Yes, the project is a side project, but quite a few people have set up RSS feeds, so I try to make sure preprints are getting indexed accurately.  If something happens to my web server or to me the production code is open source and anyone who knows how to deploy a Django application shouldn't have too much trouble setting up their own version of it.

**Comment by aleimba** [comment]
Is PrePubMed publishable? A paper or a preprint (PeerJ?) would certainly speak to the more traditional folks.

You could also contact NCBI's Pubmed what they think about that, maybe they can include some of your code (although very unlikely) or ideas? You would have to talk to them before a possible publication anyway, I guess.

**Comment by OmnesRes** [comment]
The search.biopreprint people published their tool, so I imagine I could publish mine, I just don't really see what it contributes to the literature.  PrePubMed simply indexes the preprint servers with web scraping, and has a search function that only partially mimics PubMed's search.

When I responded to the NIH RFI on preprints I mentioned I thought they should index preprints:
http://www.omnesres.com/blog/rfi/

My understanding is that PubMed does not have automated indexing, but the journals have to submit the information themselves.  This would be more work for the maintainers of the preprint servers who might already be at capacity, for example bioRxiv has to screen over 20 preprints per day.

This points to the need of ASAPbio's Central Service.  Perhaps they would have the time to organize all the data needed for PubMed indexing.  The Central Service is still some time away though, and if I join a research group that is interested in further developing PrePubMed maybe it will have enough features to warrant a publication.

**Review by pschloss — COMMENTED** [review]
Thanks again for your comments and feedback. I'm not going to accept the PR directly, but I have incorporated your feedback in the version I am using to integrate feedback from others.

**Pull request closed without merging**
